version: '3.8'
services:
  postgres-db:
    image: postgres:13-alpine
    container_name: postgres-db
    restart: always
    command: -c "log_statement=all"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # ports:
    #   - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      zs_network:

  logsearchapi:
    build: ../logsearchapi
    container_name: logsearchapi
    depends_on:
      - postgres-db
    ports:
      - 8080:8080
    environment:
      LOGSEARCH_PG_CONN_STR: "postgres://postgres:postgres@postgres-db/postgres?sslmode=disable"
      LOGSEARCH_AUDIT_AUTH_TOKEN: 1234
      MINIO_LOG_QUERY_AUTH_TOKEN: 1234
      LOGSEARCH_DISK_CAPACITY_GB: 5
    links:
      - postgres-db
    networks:
      zs_network:

  minioserver:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: minioserver
    ports:
      - 9000:9000
    command: ["minio", "gateway", "zcn"]
    environment:
      MINIO_AUDIT_WEBHOOK_ENDPOINT: http://logsearchapi:8080/api/ingest?token=1234
      MINIO_AUDIT_WEBHOOK_AUTH_TOKEN: 1234
      MINIO_AUDIT_WEBHOOK_ENABLE: "on"
      MINIO_ROOT_USER: rootroot
      MINIO_ROOT_PASSWORD: rootroot
      MINIO_BROWSER: "OFF"
      MINIO_ETCD_ENDPOINTS: http://etcd:2379
      MINIO_NOTIFY_POSTGRES_ENABLE_PRIMARY: "on"
      MINIO_NOTIFY_POSTGRES_CONNECTION_STRING_PRIMARY: "postgres://postgres:postgres@postgres-db/postgres?sslmode=disable"
      MINIO_NOTIFY_POSTGRES_TABLE_PRIMARY: "minioevents"
      MINIO_NOTIFY_POSTGRES_FORMAT_PRIMARY: "namespace"
    links:
      - logsearchapi:logsearchapi
    volumes:
      - ~/.zcn:/root/.zcn
    networks:
      zs_network:

  minioclient:
    build: ../client-api
    container_name: minioclient
    depends_on:
      - minioserver
    ports:
      - 3001:3001
    environment:
      MINIO_SERVER: "minioserver:9000"
    networks:
      zs_network:

  etcd:
    image: 'bitnami/etcd:latest'
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      zs_network:

volumes:
  db:
    driver: local

networks:
  zs_network:
    driver: bridge
