---
# tasks file for local_sys_req
- name: update local system all packages to their latest version
  apt:
    name: "*"
    state: latest 

- name: Install build-essential and git
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - build-essential
    - git

- name: Clone zwalletcli
  git:
    repo: 'https://github.com/0chain/zwalletcli.git'
    dest: "{{ lookup('env', 'PWD') }}/zwalletcli"

- name: Clone zboxcli
  git:
    repo: 'https://github.com/0chain/zboxcli.git'
    dest: "{{ lookup('env', 'PWD') }}/zboxcli"
    force: yes

- name: Install zwalletcli and zboxcli
  make:
    chdir: "{{ item }}"
    target: install
  loop:
    - "{{ lookup('env', 'PWD') }}/zwalletcli"
    - "{{ lookup('env', 'PWD') }}/zboxcli"

- name: Clone minio
  git:
    repo: 'https://github.com/0chain/minio.git'
    dest: "{{ lookup('env', 'PWD') }}/minio"

- name: create minio binary
  shell: |
    cd {{ lookup('env', 'PWD') }}/minio
    go mod tidy
    go build .
