name: Change Script Image Tag

# Only trigger, when the build workflow succeeded !
on:
  workflow_run:
    workflows: ["build-&-publish-minio-client-docker-image", "build-&-publish-minio-logsearchapi-docker-image", "build-&-publish-minio-docker-image"]
    types:
      - completed

jobs:
  notify:
    runs-on: arc-runner

    steps:
      - uses: actions/checkout@v2